{
    'name': 'Legal Practice Management - POA',
    'version': '1.0.0',
    'summary': 'Manage reusable power of attorney authorities on client records.',
    'description': 'Adds reusable POA authorities, lets staff assign them to clients, and provides direct one-time POA document downloads from the client form.',
    'author': 'Mohamed Essam',
    'website': 'https://essamsalem.com',
    'category': 'Contacts',
    'depends': ['base', 'contacts', 'legal_practice_management', 'alnas_docx'],
    'data': [
        'security/ir.model.access.csv',
        'views/poa_permission_views.xml',
        'views/poa_download_wizard_view.xml',
        'views/res_partner_poa_view.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'images': [],
    'demo': [],
    'test': [],
    'css': [],
    'js': [],
    'qweb': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'sequence': 1,
}


